name: Spellcheck Action

on: push

permissions:
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.66.0
        with:
          sources_files: README.md
          task_name: Markdown

